export const ourproductArray =[
    {
        discountbtn: false,
        discountprice: 40,
        TrashIcon: false,
        HeaterIcon: true,
        EyeIcon: true,
        src : "/dogfood.png",
        Heading: "HAVIT HV-G92 Gamepad",
        price: 100,  
        star: 5,
        reviews: 35,
        colorDiv: false,
    },

    {
        discountbtn: false,
        discountprice: 40,
        TrashIcon: false,
        HeaterIcon: true,
        EyeIcon: true,
        src : "/camera.png",
        Heading: "CANON EOS DSLR Camera",
        price: 100,
        star: 3,
        reviews: 35,
        colorDiv: false,
    },
    {
        discountbtn: false,
        discountprice: 40,
        TrashIcon: false,
        HeaterIcon: true,
        EyeIcon: true,
        src : "/laptop.png",
        Heading: "HAVIT HV-G92 Gamepad",
        price: 100,
        
        star: 5,
        reviews: 35
    },
    {
        discountbtn: false,
        discountprice: 40,
        TrashIcon: false,
        HeaterIcon: true,
        EyeIcon: true,
        src : "/creams.png",
        Heading: "HAVIT HV-G92 Gamepad",
        price: 100,
        
        star: 5,
        reviews: 35
    },
    {
        discountbtn: true,
        discountprice: "New",
        TrashIcon: false,
        HeaterIcon: true,
        EyeIcon: true,
        src : "/car.png",
        Heading: "HAVIT HV-G92 Gamepad",
        price: 100,
        
        star: 5,
        reviews: 35, colorDiv: true,
        color1: "bg-black",
        color2: "red"
    },
    {
        discountbtn: false,
        discountprice: 40,
        TrashIcon: false,
        HeaterIcon: true,
        EyeIcon: true,
        src : "/shoes.png",
        Heading: "HAVIT HV-G92 Gamepad",
        price: 100,
        
        star: 5,
        reviews: 35,
        colorDiv: true,
        color1: "bg-black",    
        color2: "red",
    },
    {
        discountbtn:true,
        discountprice: "New",
        TrashIcon: false,
        HeaterIcon: true,
        EyeIcon: true,
        src : "/usbgamepad.png",
        Heading: "HAVIT HV-G92 Gamepad",
        price: 100,
        
        star: 5,
        reviews: 35,
        colorDiv: true,
        color1: "bg-black",    
        color2: "red",
    },
    {
        discountbtn: false,
        discountprice: 40,
        TrashIcon: false,
        HeaterIcon: true,
        EyeIcon: true,
        src : "/satinjacket.png",
        Heading: "HAVIT HV-G92 Gamepad",
        price: 100,
        
        star: 5,
        reviews: 35,   colorDiv: true,
        color1: "bg-black",
        color2: "orange",
    },
]